config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'contracts#home'

  get "/work_statuses", to: 'contracts#work_statuses'
  
  get "/planning", to: 'contracts#planning'
  
  resources :contracts do
    resources :elevators
    collection do
      get :history
      get :modal
    end
  end
  
  get 'charts', to: 'charts#index'
  
  resources :quality_issues
end

app/models/contract.rb
# == Schema Information
#
# Table name: contracts
#
#  id                   :bigint           not null, primary key
#  actual_end_at        :date
#  actual_start_at      :date
#  customer_name        :string
#  eng_required_date_at :date
#  entry_date           :date
#  job_name             :string           not null
#  job_number           :string           not null
#  selling_price        :float
#  weeks_engineering    :date
#  weeks_estimate       :date
#  work_status          :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
# Indexes
#
#  index_contracts_on_job_number  (job_number) UNIQUE
#
class Contract < ApplicationRecord
    validates :job_name, :job_number, :actual_end_at, :actual_start_at, 
              :customer_name, :eng_required_date_at, :entry_date, 
              :selling_price, :weeks_engineering, :weeks_estimate,
              :work_status,  presence: true

    validates :job_number, uniqueness: true

    has_many :elevators, dependent: :destroy

    has_many :change_logs, dependent: :destroy
    
    has_many :quality_issues

    enum work_status: {
        preliminar: 0,
        markups: 1,
        final: 2,
        buyout: 3,
        others: 4,
        customer: 5,
        waiting: 6
      }

    accepts_nested_attributes_for :elevators
    
    after_save :log_work_status_change, if: :saved_change_to_work_status?


    def self.search(params)
      base_query = self.includes(:elevators)
      
      return base_query if params[:query].blank?
    
      search_term = "%#{sanitize_sql_like(params[:query])}%"
      work_status_value = Contract.work_statuses[params[:query]]
    
      if work_status_value
        base_query.where(work_status: work_status_value)
      else
        base_query.where("job_number LIKE :search OR customer_name LIKE :search OR job_name LIKE :search", 
                         search: search_term)
      end
    end
    
    def self.contracts_count_by_status
      group(:work_status).count
    end

    def all_elevator_types
      if elevators.any?
        elevators.map(&:elevator_type).join(', ')
      else
        'No elevator type'
      end
    end

    def all_descriptions
      if elevators.size > 0
        elevators.map(&:description).join(', ')
      else
        'No description provided'
      end
    end

    private

    def log_work_status_change
      # don't need id since we are working with a ActiveRecord association
      change_logs.create(old_work_status: work_status_before_last_save, new_work_status: work_status)
    end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: %i[ show edit update destroy ]
  
  skip_before_action :authenticate_user!, only: :home


  def home
  end

  # GET /contracts or /contracts.json
  def index
    # add index to speed up search
    # Postgres db has a search feature
    # explore gems for search like algolia or https://www.meilisearch.com/
    # check if the lenght arrays is zero don't show headers
    if params[:query].present?
      @contracts = Contract.includes(:elevators).search(params)
    elsif params[:work_status].present?
      @contracts = Contract.includes(:elevators).where(work_status: params[:work_status])
    else
      @contracts = Contract.includes(:elevators).all
    end
  end

  # GET /contracts/1 or /contracts/1.json
  def show
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
    @contract.elevators.build
    # @contract.elevators.work_status = WorkStatus.new
    # debugger
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts or /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        format.html { redirect_to @contract, notice: "Contract was successfully created." }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1 or /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to contract_url(@contract), notice: "Contract was successfully updated." }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1 or /contracts/1.json
  def destroy
    @contract.destroy

    respond_to do |format|
      format.html { redirect_to contracts_url, notice: "Contract was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def work_statuses 
    # where do i get the Contract data?
    # scope is another option or helper method
    contract_statuses_stats
  end

  def planning
    contract_statuses_stats
  
    @statuses = %w[preliminar markups final buyout others customer waiting]
    @contracts_by_status = {}
    @all_contracts = Contract.includes(:elevators).all.to_a
    @contracts = @all_contracts
  
    @statuses.each do |status|
      @contracts_by_status[status] = @all_contracts.select { |contract| contract.work_status == status }
    end

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Report planning, date: #{Time.now.strftime("%d/%m/%Y")}", template: "contracts/planning_pdf", formats: [:html], 
        orientation: 'Landscape'
      end
    end
  end

  def history
    @contracts = Contract.includes(:elevators).all
    @change_logs = ChangeLog.order(created_at: :asc)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      @contract = Contract.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contract_params
      params.require(:contract).permit(:job_name, :job_number, :customer_name, :selling_price, 
                                       :eng_required_date_at, :actual_start_at, :actual_end_at, 
                                       :work_status, :entry_date, :weeks_estimate, :weeks_engineering, 
                                       elevators_attributes: [:id, :subdivision, :description, :elevator_type])
    end

    def contract_statuses_stats
      @work_statuses = Contract.work_statuses
      @work_statuses_count = Contract.group(:work_status).count
    end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_contract.html.erb
<div id="<%= dom_id contract %>">
  <tbody>
    <tr class="bg-white border-b">
      <th scope="row" class="px-2 text-sm">
        <%= contract_counter + 1 %>.
      </th>
      <td class="px-2 text-sm">
        <%= link_to contract.customer_name, contract_path(contract), 
            class: "text-blue-500 underline underline-offset-4", 
            data: { turbo_frame: "_top" } %>
      </td>
      <td class="px-2 text-sm">
        <%= contract.job_number %>
      </td>
      <td class="px-2 text-sm">
        <%= contract.job_name %>
      </td>
      <td class="px-2 text-sm">
        <%= number_to_currency(contract.selling_price, precision: 0) %>
      </td>
      <td class="px-2 text-sm">
        <%= contract.all_descriptions.truncate_words(4) %>
      </td>
      <td class="px-2 text-sm">
        <%= contract.all_elevator_types %>
      </td>
      <td class="px-2 text-sm">
        <%= contract.work_status.capitalize %>
      </td>
      <td class="px-2 text-sm">
        <%= contract.created_at.strftime("%d/%m/%Y") %>
      </td>
      <td class="px-2 text-sm">
        <%= contract.weeks_estimate.strftime("%d/%m/%Y") %>
      </td>
      <td class="px-2 text-sm">
        <%= contract.eng_required_date_at.strftime("%d/%m/%Y") %>
      </td>
      <td class="px-2 text-sm">
      </td>
      <td class="px-2 text-sm">
        <%= contract.entry_date.strftime("%d/%m/%Y") %>
      </td>
      <td class="px-2 text-sm">
        <%= contract.entry_date.strftime("%d/%m/%Y") %>
      </td>
      <td class="px-2 text-sm">
        <%= contract.entry_date.strftime("%d/%m/%Y") %>
      </td>
      <td class="px-2 text-sm">
        <%= contract.entry_date.strftime("%d/%m/%Y") %>
      </td>
      <td class="px-2 text-sm">
        <%= contract.entry_date.strftime("%d/%m/%Y") %>
      </td>
      <td class="px-2 text-sm">
        <%= (contract.weeks_engineering - contract.entry_date).to_i / 7 %>
      </td>
    </tr>
  </tbody>
</div>

app/views/contracts/_contract_show.html.erb
<div class="flex justify-around">
  <div class="mr-12">
    <div class="my-5">
      <strong>Job Name:</strong>
      <p class="block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80">
        <%= contract.job_name %>
      </p>
    </div>

    <div class="my-5">
      <strong>Job Number:</strong>
      <p class="block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80">
        <%= contract.job_number %>
      </p>
    </div>

    <div class="my-5">
      <strong>Customer Name:</strong>
      <p class="block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80">
        <%= contract.customer_name %>
      </p>
    </div>

    <div class="my-5">
      <strong>Selling Price:</strong>
      <p class="block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80">
        <%= number_to_currency(contract.selling_price, precision: 0) %>
      </p>
    </div>

    <div class="my-5">
      <strong>Work Status:</strong>
      <p class="block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80">
        <%= contract.work_status.capitalize %>
      </p>
    </div>

    <div class="flex flex-col">
      <%= link_to 'Add Elevator 🛗', new_contract_elevator_path(@contract), class: "w-44 rounded-lg py-3 px-5 bg-sapiBlue text-white inline-block font-medium" %>

      <%= link_to 'Edit this contract', edit_contract_path(@contract), class: "w-44 mt-2 rounded-lg py-3 px-5 bg-gray-300 inline-block font-medium" %>
      
      <%= link_to 'Back ↩️', contracts_path, class: "mt-2 w-28 rounded-lg py-3 px-5 bg-gray-300 inline-block font-medium" %>
    </div>

  </div>

  <div class="ml-12">
    <div class="my-5">
      <strong>Engineering Required Date:</strong>
      <p class="block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80">
        <%= contract.eng_required_date_at.strftime("%d/%m/%Y") %>
      </p>
    </div>

    <div class="my-5">
      <strong>Actual Start Date:</strong>
      <p class="block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80">
        <%= contract.actual_start_at.strftime("%d/%m/%Y") %>
      </p>
    </div>

    <div class="my-5">
      <strong>Actual End Date:</strong>
      <p class="block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80">
        <%= contract.actual_end_at.strftime("%d/%m/%Y") %>
      </p>
    </div>

    <div class="my-5">
      <strong>Entry Date:</strong>
      <p class="block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80">
        <%= contract.entry_date.strftime("%d/%m/%Y") %>
      </p>
    </div>

    <div class="my-5">
      <strong>Weeks Estimate:</strong>
      <p class="block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80">
        <%= contract.weeks_estimate.strftime("%d/%m/%Y") %>
      </p>
    </div>

    <div class="my-5">
      <strong>Weeks Engineering:</strong>
      <p class="block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80">
        <%= contract.weeks_engineering.strftime("%d/%m/%Y") %>
      </p>
    </div>

    <%= button_to 'Destroy this contract', contract_path(@contract), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-500 font-medium text-white",
    data: { turbo_method: :delete, turbo_confirm: "Really?!" } %>

  </div>
  <!-- Elevators associated with the contract -->
  <div class="my-5 ml-24">
    <strong>Elevators: (<%= @contract.elevators.count %>) </strong>
    <% contract.elevators.each_with_index do |elevator, index| %>
      <div class="mt-2 p-2 border border-sapiBlue rounded-md">
        <p><strong> <%= "#{index + 1}. " %> Description:</strong> <%= link_to elevator.description, contract_elevator_path(@contract, elevator), class: "text-blue-600 underline" %></p>
        <p><strong>Type:</strong> <%= elevator.elevator_type %> </p>
        <p><strong>Subdivision:</strong> <%= elevator.subdivision %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/contracts/_form.html.erb
<%= form_with(model: contract, class: "contents") do |form| %>
  <% if contract.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
        <% contract.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex justify-around">
    <div class="mr-12">
      <div class="my-5">
        <%= form.label :job_name %>
        <%= form.text_field :job_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80" %>
      </div>

      <div class="my-5">
        <%= form.label :job_number %>
        <%= form.text_field :job_number, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80" %>
      </div>

      <div class="my-5">
        <%= form.label :customer_name %>
        <%= form.text_field :customer_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80" %>
      </div>

      <div class="my-5">
        <%= form.label :selling_price %>
        <%= form.number_field :selling_price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80" %>
      </div>

      <%# for later use the field below %>
      <%# <%= form.date_field :test %>

      <div class="my-5">
        <%= form.label :work_status %>
        <%= form.select :work_status, Contract.work_statuses.map { |ws| [ws[0]] }, { include_blank: "Select a work status." }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80" %>
      </div>
      <div class="inline">
        <%= form.submit class: "rounded-lg py-3 px-5 bg-sapiBlue text-white inline-block font-medium cursor-pointer mt-6" %>
      </div>

      <%= link_to 'Back ↩️', contracts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>

    <div class="ml-12">
      <div class="my-5">
        <%= form.label :eng_required_date_at %>
        <%= form.date_field :eng_required_date_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80" %>
      </div>

      <div class="my-5">
        <%= form.label :actual_start_at %>
        <%= form.date_field :actual_start_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80" %>
      </div>

      <div class="my-5">
        <%= form.label :actual_end_at %>
        <%= form.date_field :actual_end_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80" %>
      </div>

      <div class="my-5">
        <%= form.label :entry_date %>
        <%= form.date_field :entry_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80" %>
      </div>

      <div class="my-5">
        <%= form.label :weeks_estimate %>
        <%= form.date_field :weeks_estimate, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80" %>
      </div>

      <div class="my-5">
        <%= form.label :weeks_engineering %>
        <%= form.date_field :weeks_engineering, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80" %>
      </div>
    </div>
    <!-- Elevators associated with the contract -->
    <% if contract.elevators.any? && action_name != "new" && controller_name != "contracts" %>
      <div class="my-5 ml-24">
        <strong>Elevators: (<%= @contract.elevators.count %>) </strong>
        <% contract.elevators.each_with_index do |elevator, index| %>
          <div class="mt-2 p-2 border border-sapiBlue rounded-md">
            <p><strong> <%= "#{index + 1}. " %> Description:</strong> <%= link_to elevator.description, contract_elevator_path(@contract, elevator), class: "text-blue-600 underline" %></p>
            <p><strong>Type:</strong> <%= elevator.elevator_type %> </p>
            <p><strong>Subdivision:</strong> <%= elevator.subdivision %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/contracts/_sidebar-2.html.erb
<aside class="bg-sapiGray w-48 sticky top-24 h-[calc(100vh-96px)]">
  <div class="flex justify-center items-center h-12 hover:border-2 border-white w-36 ml-2">
    <%= link_to 'New contract' do %>
      <%= svg_tag "square-plus-regular", style: "color: #1a5294; font-size: 30px; margin: 0 15px; margin-left: 8px;" %>
    <% end %>
    <%= link_to "New project", new_contract_path, class: "text-xs hover:text-sm", style: "color: #1a5294;" %>
  </div>
  <div class="flex justify-center items-center h-12 hover:border-2 border-white w-36 ml-2">
    <%= link_to modal_contracts_path, data: { turbo_frame: "modal" } do %>
      <%= svg_tag "pen-to-square-solid", style: "color: #1a5294; font-size: 30px; margin-right: 18px;" %>
    <% end %>
    <%= link_to "Edit project", modal_contracts_path, class: "text-xs -ml-2 hover:text-sm", style: "color: #1a5294; margin-right: -5px;", data: { turbo_frame: "modal" } %>
  </div>
  <div class="flex justify-center items-center h-12 hover:border-2 border-white w-36 ml-4">
    <%= link_to modal_contracts_path, data: { turbo_frame: "modal" } do %>
      <%= svg_tag "arrows-turn-to-dots-solid", style: "color: #1a5294; font-size: 30px;" %>
    <% end %>
    <%= link_to "Move project", modal_contracts_path, class: "text-xs hover:text-sm", style: "color: #1a5294; margin-left: 10px;", data: { turbo_frame: "modal" } %>
  </div>
  <div class="flex justify-center items-center h-12 hover:border-2 border-white w-36 ml-2">
    <%= link_to history_contracts_path do %>
      <%= svg_tag "box-archive-solid", style: "color: #1a5294; font-size: 30px; margin: 0 15px; margin-left: -7px;" %>
    <% end %>
    <%= link_to "History", history_contracts_path, class: "text-xs hover:text-sm", style: "color: #1a5294;" %>
  </div>
  <div class="flex justify-center items-center h-12 hover:border-2 border-white w-36 ml-2">
    <%= link_to planning_path(format: :pdf) do %>
      <%= svg_tag "print-solid", style: "color: #1a5294; font-size: 30px; margin: 0 15px;" %>
    <% end %>
    <%= link_to "Print report", planning_path(format: :pdf), class: "text-xs hover:text-sm", style: "color: #1a5294;" %>
  </div>
</aside>

app/views/contracts/_sidebar.html.erb
<aside class="bg-sapiGray w-48 sticky top-24 h-[calc(100vh-96px)]">

  <%# this code was initially design to iterate over the work_statuses however it wont work  %>
  <%# because i need a svg_icon for each status %>

  <%# <% @work_statuses.each_key do |status| %>
    <%# <%= link_to status.capitalize, contracts_path(work_status: status) %>
    <%# <br> %>
  <%# <% end %>

  <%# this code works but it's not dynamic %>

  <div class="flex items-center h-12 hover:border-2 border-white">
    <%= link_to contracts_path(work_status: "preliminar") do %>
      <%= svg_tag "copy-regular", style: "color: #1a5294; font-size: 30px; margin: 0 15px;" %>
    <% end %>
    <%= link_to "PRELIMINAR", contracts_path(work_status: "preliminar"), class: "text-xs -ml-2 hover:text-sm", style: "color: #1a5294;" %>
  </div>
  <div class="flex items-center mt-2 h-12 hover:border-2 border-white">
    <%= link_to contracts_path(work_status: "markups") do %>
      <%= svg_tag "pen-to-square-regular", style: "color: #1a5294; font-size: 30px; margin: 0 15px;" %>
    <% end %>
    <%= link_to "MARKUPS", contracts_path(work_status: "markups"), class: "text-xs -ml-2 hover:text-sm", style: "color: #1a5294;" %>
  </div>
  <div class="flex items-center mt-2 h-12 hover:border-2 border-white">
    <%= link_to contracts_path(work_status: "final") do %>
      <%= svg_tag "flag-checkered-solid", style: "color: #1a5294; font-size: 30px; margin: 0 15px;" %>
    <% end %>
    <%= link_to "FINAL", contracts_path(work_status: "final"), class: "text-xs -ml-2 hover:text-sm", style: "color: #1a5294;" %>
  </div>
  <div class="flex items-center mt-2 h-12 hover:border-2 border-white">
    <%= link_to contracts_path(work_status: "buyout") do %>
      <%= svg_tag "building-solid", style: "color: #1a5294; font-size: 30px; margin: 0 15px;" %>
    <% end %>
    <%= link_to "BUYOUT", contracts_path(work_status: "buyout"), class: "text-xs -ml-2 hover:text-sm", style: "color: #1a5294;" %>
  </div>
  <div class="flex items-center mt-2 h-12 hover:border-2 border-white">
    <%= link_to contracts_path(work_status: "others") do %>
      <%= svg_tag "chart-line-solid", style: "color: #1a5294; font-size: 30px; margin: 0 15px;" %>
    <% end %>
    <%= link_to "OTHERS", contracts_path(work_status: "others"), class: "text-xs -ml-2 hover:text-sm", style: "color: #1a5294;" %>
  </div>
  <div class="flex items-center mt-2 h-12 hover:border-2 border-white">
    <%= link_to contracts_path(work_status: "waiting") do %>
      <%= svg_tag "pause-solid", style: "color: #1a5294; font-size: 30px; margin: 0 15px;" %>
    <% end %>
    <%= link_to "WAITING", contracts_path(work_status: "waiting"), class: "text-xs -ml-2 hover:text-sm", style: "color: #1a5294;" %>
  </div>
  <div class="flex items-center mt-2 h-12 hover:border-2 border-white">
    <%= link_to contracts_path(work_status: "customer") do %>
      <%= svg_tag "building-solid", style: "color: #1a5294; font-size: 30px; margin: 0 15px;" %>
    <% end %>
    <%= link_to "CUSTOMER", contracts_path(work_status: "customer"), class: "text-xs -ml-2 hover:text-sm", style: "color: #1a5294;" %>
  </div>
</aside>
  

app/views/contracts/_table_contracts.html.erb
<div class="flex justify-between items-center">
  <h1 class="font-bold text-4xl mt-4">
      <%= title.nil? ? "Search result" : title.capitalize %>
  </h1>
</div>
<%= turbo_frame_tag "search_results" do %>
  <%= render partial: "table_jobs", locals: { contracts: contracts } %>
<% end %>

app/views/contracts/history.html.erb
<%= render partial: "sidebar-2" %>
<div class="w-full p-4">

  <div id="contracts" class="flex mt-4">
    <div class="mr-8 overflow-x-auto shadow-md sm:rounded-lg">
      <table class="text-sm text-left text-gray-500">
        <thead class="text-xs uppercase bg-gray-400 text-black ">
          <tr>
            <th scope="col" class="px-2">
                No.
            </th>
            <th scope="col" class="px-4 whitespace-nowrap">
                Project name
            </th>
            <th scope="col" class="px-2">
                Number
            </th>
            <th scope="col" class="px-2">
                Company
            </th>
            <th scope="col" class="px-2">
                Price
            </th>
            <th scope="col" class="px-2">
                Description
            </th>
            <th scope="col" class="px-2">
                Type
            </th>
            <th scope="col" class="px-2">
                Status
            </th>
            <th scope="col" class="px-2">
                By
            </th>
            <th scope="col" class="px-2">
                Estim.
            </th>
            <th scope="col" class="px-2">
                Eng.
            </th>
            <th scope="col" class="bg-white text-white px-2">
            </th>
            <th scope="col" class="px-2 py-4 whitespace-nowrap">
                Job inn
            </th>
            <th scope="col" class="px-2">
                Rel Req
            </th>
            <th scope="col" class="px-2">
                Start
            </th>
            <th scope="col" class="px-2">
                Rel DWG
            </th>
            <th scope="col" class="px-2">
                Sal
            </th>
            <th scope="col" class="px-2">
                WRK DAYS
            </th>
          </tr>
        </thead>
          <tbody>
            <% @contracts.each_with_index do |contract, contract_counter| %>

              <!-- Find all change logs related to this contract -->
              <% relevant_change_logs = @change_logs.select { |log| log.contract_id == contract.id } %>

              <!-- Display change logs for this contract -->
              <% relevant_change_logs.each do |change_log| %>
                <tr class="bg-yellow-100 border-b">
                  <!-- The row number and most columns will remain the same -->
                  <th scope="row" class="px-2 text-sm">
                    <%= contract_counter + 1 %>.
                  </th>
                  <td class="px-2 text-sm">
                    <%= link_to contract.customer_name, contract_path(contract), 
                        class: "text-blue-500 underline underline-offset-4", 
                        data: { turbo_frame: "_top" } %>
                  </td>
                  <td class="px-2 text-sm">
                    <%= contract.job_number %>
                  </td>
                  <td class="px-2 text-sm">
                    <%= contract.job_name %>
                  </td>
                  <td class="px-2 text-sm">
                    <%= number_to_currency(contract.selling_price, precision: 0) %>
                  </td>
                  <td class="px-2 text-sm">
                    <%= contract.all_descriptions.truncate_words(4) %>
                  </td>
                  <td class="px-2 text-sm">
                    <%= contract.all_elevator_types %>
                  </td>
                  <td class="px-2 text-sm">
                    <%= change_log.new_work_status.capitalize %>
                  </td>
                  <td class="px-2 text-sm">
                    <%= contract.created_at.strftime("%d/%m/%Y") %>
                  </td>
                  <td class="px-2 text-sm">
                    <%= contract.weeks_estimate.strftime("%d/%m/%Y") %>
                  </td>
                  <td class="px-2 text-sm">
                    <%= contract.eng_required_date_at.strftime("%d/%m/%Y") %>
                  </td>
                  <td class="px-2 text-sm bg-white">
                  </td>
                  <td class="px-2 text-sm">
                    <%= contract.entry_date.strftime("%d/%m/%Y") %>
                  </td>
                  <td class="px-2 text-sm">
                    <%= contract.entry_date.strftime("%d/%m/%Y") %>
                  </td>
                  <td class="px-2 text-sm">
                    <%= contract.entry_date.strftime("%d/%m/%Y") %>
                  </td>
                  <td class="px-2 text-sm">
                    <%= contract.entry_date.strftime("%d/%m/%Y") %>
                  </td>
                  <td class="px-2 text-sm">
                    <%= contract.entry_date.strftime("%d/%m/%Y") %>
                  </td>
                  <td class="px-2 text-sm">
                    <%= (contract.weeks_engineering - contract.entry_date).to_i / 7 %>
                  </td>
                </tr>
              <% end %>

            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>