config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'contracts#home'

  get "/work_statuses", to: 'contracts#work_statuses'
  
  get "/planning", to: 'contracts#planning'
  
  resources :contracts do
    resources :elevators
    collection do
      get :history
      get :modal
    end
  end
  
  get 'charts', to: 'charts#index'
  
  resources :quality_issues
end

app/models/elevator.rb
# == Schema Information
#
# Table name: elevators
#
#  id            :bigint           not null, primary key
#  description   :text
#  elevator_type :integer
#  subdivision   :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  contract_id   :bigint           not null
#
# Indexes
#
#  index_elevators_on_contract_id  (contract_id)
#
# Foreign Keys
#
#  fk_rails_...  (contract_id => contracts.id)
#
class Elevator < ApplicationRecord
  validates :description, :subdivision, :elevator_type, presence: true
  validates :contract_id, presence: true

  belongs_to :contract

  enum elevator_type: {
    T1: 0,
    T2: 1,
    T3: 2,
    T4: 3,
    T5: 4
  }
end

app/controllers/elevators_controller.rb
class ElevatorsController < ApplicationController
  before_action :set_contract
  before_action :set_elevator, only: %i[ show edit update destroy ]

  # GET /elevators or /elevators.json
  def index
    @contract = Contract.find(params[:contract_id])
    @elevators = @contract.elevators
  end

  # GET /elevators/1 or /elevators/1.json
  def show
  end

  # GET /elevators/new
  def new
    @elevator = @contract.elevators.new
    # @elevator.work_statuses.build
  end

  # GET /elevators/1/edit
  def edit
  end

  # POST /elevators or /elevators.json
  def create
    @elevator = @contract.elevators.new(elevator_params)
    respond_to do |format|
      if @elevator.save
        format.html { redirect_to contract_path(@contract), notice: "Elevator was successfully created." }
        format.json { render :show, status: :created, location: @elevator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @elevator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elevators/1 or /elevators/1.json
  def update
    respond_to do |format|
      if @elevator.update(elevator_params)
        format.html { redirect_to contract_elevator_path(@contract, @elevator), notice: "Elevator was successfully updated." }
        format.json { render :show, status: :ok, location: @elevator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @elevator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elevators/1 or /elevators/1.json
  def destroy
    @elevator.destroy

    respond_to do |format|
      format.html { redirect_to contract_elevators_path(@contract), notice: "Elevator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elevator
      @elevator = @contract.elevators.find(params[:id])
    end

    def set_contract
      @contract = Contract.find(params[:contract_id])
    end

    # Only allow a list of trusted parameters through.
    def elevator_params
      params.require(:elevator).permit(:elevator_type, :description, :subdivision, :contract_id)
    end
end

app/helpers/elevators_helper.rb
module ElevatorsHelper
end

app/views/elevators/_elevator.html.erb
<div id="<%= dom_id elevator %>" class="bg-white p-6 rounded-lg shadow-lg w-full mx-auto mt-10">

  <h2 class="text-2xl font-bold mb-6 text-center">Elevator Details</h2>

  <div class="mb-5">
    <strong class="block font-medium mb-2 text-gray-600">Type:</strong>
    <span class="text-gray-800"><%= elevator.elevator_type %></span>
  </div>

  <div class="mb-5">
    <strong class="block font-medium mb-2 text-gray-600">Description:</strong>
    <span class="text-gray-800"><%= elevator.description %></span>
  </div>

  <div class="mb-5">
    <strong class="block font-medium mb-2 text-gray-600">Subdivision:</strong>
    <span class="text-gray-800"><%= elevator.subdivision %></span>
  </div>

  <div class="mb-5">
    <strong class="block font-medium mb-2 text-gray-600">Contract:</strong>
    <span class="text-gray-800"><%= elevator.contract_id %></span>
  </div>
  
</div>

app/views/elevators/_form.html.erb
<%= form_with(model: [@contract, elevator], class: "contents p-5 bg-white shadow-lg rounded-md") do |form| %>

  <% if elevator.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(elevator.errors.count, "error") %> prohibited this elevator from being saved:</h2>

      <ul class="list-disc pl-5">
        <% elevator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :elevator_type, class: "block font-medium text-gray-700" %>
    <%= form.select :elevator_type, [['T1'], ['T2'], ['T3'],['T4'], ['T5']], { include_blank: "Select elevator type." }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full transition-all duration-200 ease-in-out focus:border-blue-500" %>
  </div>

  <div class="my-5">
    <%= form.label :description, class: "block font-medium text-gray-700" %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full transition-all duration-200 ease-in-out focus:border-blue-500" %>
  </div>

  <div class="my-5">
    <%= form.label :subdivision, class: "block font-medium text-gray-700" %>
    <%= form.text_field :subdivision, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full transition-all duration-200 ease-in-out focus:border-blue-500" %>
  </div>

  <div class="mt-6">
    <%= form.submit "Save", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer hover:bg-blue-700 active:bg-blue-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
      <%= link_to "Back to elevator", contract_path(@contract), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% if !@elevator.new_record? %>
    <% end %> 
  </div>

<% end %>

app/views/elevators/edit.html.erb
<%= render partial: "/contracts/sidebar-2" %>

<div class="mx-auto w-1/3 mt-4">
  <h1 class="font-bold text-4xl">Editing elevator</h1>

  <%= render "form", elevator: @elevator %>

</div>

app/views/elevators/index.html.erb
<div class="mx-auto w-1/3 mt-4">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="my-4">
    <h1 class="font-bold text-4xl"> <%= @contract.job_name %> Elevators</h1>
    <%= render @elevators %>
  </div>
  
</div>

app/views/elevators/new.html.erb
<%= render partial: "/contracts/sidebar-2" %>

<div class="mx-auto w-1/3">
  <h1 class="font-bold text-4xl mt-4">New elevator</h1>

  <%= render "form", elevator: @elevator %>

</div>

app/views/elevators/show.html.erb
<%= render partial: "/contracts/sidebar-2" %>

<div class="flex mx-auto w-1/3">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @elevator %>

    <div class="mt-4">
      <%= link_to 'Edit this elevator', edit_contract_elevator_path(@contract, @elevator), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to 'Back ↩️', contract_path(@contract), class: "bg-gray-100 ml-2 rounded-lg py-3 px-5 inline-block font-medium" %>
      <div class="inline-block ml-2">
        <%= button_to 'Destroy this elevator', contract_elevator_path(@contract, @elevator), method: :delete, class: "text-white bg-red-500 mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
    </div>
  </div>
</div>