config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'contracts#home'

  get "/work_statuses", to: 'contracts#work_statuses'
  
  get "/planning", to: 'contracts#planning'
  
  resources :contracts do
    resources :elevators
    collection do
      get :history
      get :modal
    end
  end
  
  get 'charts', to: 'charts#index'
  
  resources :quality_issues
end

app/models/quality_issue.rb
# == Schema Information
#
# Table name: quality_issues
#
#  id          :bigint           not null, primary key
#  date        :date
#  description :text
#  resolved_at :date
#  severity    :integer
#  status      :integer          default("open")
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  contract_id :bigint           not null
#
# Indexes
#
#  index_quality_issues_on_contract_id  (contract_id)
#
# Foreign Keys
#
#  fk_rails_...  (contract_id => contracts.id)
#
class QualityIssue < ApplicationRecord
  belongs_to :contract
  
  validates :date, presence: true
  validates :description, presence: true
  validates :severity, presence: true
  validates :status, presence: true
  validates :contract_id, presence: true

  
  enum severity: { low: 0, medium: 1, high: 2, critical: 3 }

  enum status: { open: 0, pending: 1, resolved: 2 }

end

app/controllers/quality_issues_controller.rb
class QualityIssuesController < ApplicationController
  before_action :set_quality_issue, only: [:show, :edit, :update, :destroy]

  # before_action :set_contract, only: [:show, :edit, :update]


  # GET /quality_issues
  def index
    # @contract = Contract.find(params[:contract_id]) # or however you're setting it
    @quality_issues = QualityIssue.includes(:contract).all
  end
  

  # GET /quality_issues/:id
  def show
  end

  # GET /quality_issues/new
  def new
    @quality_issue = QualityIssue.new
    @contracts = Contract.all # This is to populate the dropdown for job_number and customer_name
  end

  # POST /quality_issues
  def create
    @quality_issue = QualityIssue.new(quality_issue_params)
    if @quality_issue.save
      redirect_to @quality_issue, notice: 'Quality issue was successfully created.'
    else
      render :new
    end
  end

  # GET /quality_issues/:id/edit
  def edit
  end

  # PATCH/PUT /quality_issues/:id
  def update
    if @quality_issue.update(quality_issue_params)
      redirect_to @quality_issue, notice: 'Quality issue was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /quality_issues/:id
  def destroy
    @quality_issue.destroy
    redirect_to quality_issues_url, notice: 'Quality issue was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quality_issue
      @quality_issue = QualityIssue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quality_issue_params
      params.require(:quality_issue).permit(:contract_id, :date, :description, :severity)
    end

    def set_contract
      # @contract = Contract.find(params[:contract_id])
    end
end

app/helpers/quality_issues_helper.rb
module QualityIssuesHelper

  def include_blank_option(object)
    if object.new_record?
      { include_blank: 'Please select...' }
    else
      {}
    end
  end
  
end

app/views/quality_issues/_form.html.erb
<%= form_with(model: @quality_issue, class: "contents p-5 bg-white shadow-lg rounded-md") do |form| %>
  
  <% if @quality_issue.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">>
      <h2><%= pluralize(@quality_issue.errors.count, "error") %> prohibited this quality_issue from being saved:</h2>
      
      <ul>
        <% @quality_issue.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :contract_id, "Contract number" %>
    <%= form.collection_select :contract_id, 
                               Contract.all, 
                               :id, 
                               :job_number, 
                               include_blank_option(form.object), 
                               class: 'w-full block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80' %>
  </div>

  <div class="my-5">
    <%= form.label :date %>
    <%= form.date_field :date, class: 'w-full block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80' %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'w-full block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80' %>
  </div>

  <div class="my-5">
    <%= form.label :severity %>
    <%= form.select :severity, QualityIssue.severities.keys.map { |s| [s.humanize, s] }, {}, class: 'w-full block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80' %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.select :status, ['Open', 'Pending', 'Resolved'], {}, class: "w-full block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80" %>
  </div>
  
  <div class="my-5">
    <%= form.label :resolved_at %>
    <%= form.date_field :resolved_at, class: "w-full block shadow rounded-md border border-gray-200 px-3 py-2 mt-2 w-80" %>
  </div>

  <div class="flex justify-between">
    <%= form.submit class: 'w-1/3 bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded' %>
    <%= link_to 'Back', quality_issues_path, class: ' bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded' %>
  </div>

<% end %>

app/views/quality_issues/_quality_issue.html.erb
<div id="<%= dom_id quality_issue %>" class="h-[460px] bg-white p-6 rounded-lg shadow-lg mt-10 mr-4">

  <h2 class="text-blue-600 text-2xl font-bold mb-6 text-center"><%= link_to "Quality Issue Details", quality_issue_path(quality_issue) %></h2>

  <h2 class="text-xl font-bold mb-6 text-center text-blue-400 underline"><%= link_to quality_issue.contract.customer_name.truncate_words(3), contract_path(quality_issue.contract) %></h2>

  <div class="flex mb-2 items-center">
    <span class="font-medium mb-2 text-gray-600 w-44">Contract Number:</span>
    <span><%= link_to quality_issue.contract.job_number, contract_path(quality_issue.contract) %></span>
  </div>

  <div class="flex mb-2 items-center">
    <span class="font-medium mb-2 text-gray-600 w-44">Date:</span>
    <span class="text-gray-800 w-32"><%= quality_issue.date %></span>
  </div>

  <div class="flex mb-2 items-center">
    <span class="font-medium mb-2 text-gray-600 w-44">Description:</span>
    <span class="text-gray-800 w-32"><%= quality_issue.description %></span>
  </div>

  <div class="flex mb-2 items-center">
    <span class="font-medium mb-2 text-gray-600 w-44">Severity:</span>
    <span class="text-gray-800 w-32"><%= quality_issue.severity %></span>
  </div>

  <div class="flex mb-2 items-center">
    <span class="font-medium mb-2 text-gray-600 w-44">Resolved At:</span>
    <p><%= quality_issue.resolved_at ? quality_issue.resolved_at.strftime("%d/%m/%Y") : "Not Resolved" %></p>
  </div>

  <div class="flex mb-2 items-center">
    <span class="font-medium mb-2 text-gray-600 w-44">Severity:</span>
    <p><%= quality_issue.severity.humanize %></p>
  </div>

</div>

app/views/quality_issues/edit.html.erb
<%= render partial: "/contracts/sidebar-2" %>

<div class="mx-auto w-1/3">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  
  <h1 class="font-bold text-4xl mt-4">Edit Quality Issue</h1>

  <%= render "form" %>

</div>

app/views/quality_issues/index.html.erb
<%= render partial: "/contracts/sidebar-2" %>

<div class="mx-auto ml-8 mt-4">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  
  <h1 class="font-bold text-4xl mb-4"> Quality Issues</h1>
  <%= link_to 'New Quality Issue', new_quality_issue_path, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-4' %>


  <div class="flex flex-wrap items-center">
    <%= render @quality_issues %>


  </div>
</div>

app/views/quality_issues/new.html.erb
<%= render partial: "/contracts/sidebar-2" %>

<div class="mx-auto w-1/3">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  
  <h1 class="font-bold text-4xl mt-4">New Quality Issue</h1>

  <%= render "form" %>

</div>

app/views/quality_issues/show.html.erb
<%= render partial: "/contracts/sidebar-2" %>

<div class="mx-auto w-1/3 mt-5">

  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <%= render @quality_issue %>

  <div class="mt-4">
    <%= link_to 'Edit this QA', edit_quality_issue_path(@quality_issue), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Back ↩️', quality_issues_path, class: "bg-gray-100 ml-2 rounded-lg py-3 px-5 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy', quality_issue_path(@quality_issue), method: :delete, class: "text-white bg-red-500 mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>