config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'contracts#home'

  get "/work_statuses", to: 'contracts#work_statuses'
  
  get "/planning", to: 'contracts#planning'
  
  resources :contracts do
    resources :elevators
    collection do
      get :history
      get :modal
    end
  end
  
  get 'charts', to: 'charts#index'
  
  resources :quality_issues
end

app/views/layouts/_navbar.html.erb
<header class="flex items-center bg-sapiGray h-24 sticky top-0">
  <div class="flex items-center">
    <div class="ml-4">
      <%= link_to root_path do %>
        <%= image_tag "logo.png", style: "width: 160px;" %>
      <% end %>
    </div>
    <div class="flex ml-2 items-center">
      <div class="mr-4 text-xs hover:text-sm hover:border-2 border-white">
        <%= link_to root_path do %>
          <%= svg_tag "house", style: "color: #1a5294; font-size: 30px; margin: 0 16px;" %>
          <p class="text-center text-blue-700;" style="color:#1a5294;">HOME</p>
        <% end %>
      </div>
      <div class="mr-4 text-xs hover:text-sm hover:border-2 border-white">
        <%= link_to work_statuses_path do %>
          <%= svg_tag "chart-gantt-solid", style: "color: #1a5294; font-size: 30px; margin: 0 15px;" %>
          <p class="text-center text-blue-700;" style="color:#1a5294;">STATUS</p>
        <% end %>
      </div>
      <div class="mr-4 text-xs hover:text-sm hover:border-2 border-white">
        <%= link_to planning_path do %>
          <%= svg_tag "calendar", style: "color: #1a5294; font-size: 30px; margin: 0 25px;" %>
          <p class="text-center text-blue-700;" style="color:#1a5294;">PLANNING</p>
        <% end %>
      </div>
      <div class="mr-4 text-xs hover:text-sm hover:border-2 border-white">
        <%= link_to charts_path do %>
          <%= svg_tag "chart-simple-solid", style: "color: #1a5294; font-size: 30px; margin: 0 15px;" %>
          <p class="text-center text-blue-700;" style="color:#1a5294;">CHARTS</p>
        <% end %>
      </div>
      <div class="mr-4 text-xs hover:text-sm hover:border-2 border-white">
        <%= link_to quality_issues_path do %>
          <%= svg_tag "check-to-slot-solid", style: "color: #1a5294; font-size: 25px; margin: 0 18px;" %>
          <p class="text-center text-blue-700;" style="color:#1a5294;">QUALITY</p>
        <% end %>
      </div>
      <div class="mr-4 text-xs hover:text-sm hover:border-2 border-white">
        <%= link_to work_statuses_path do %>
          <%= svg_tag "people-arrows-solid", style: "color: #1a5294; font-size: 25px; margin: 0 18px;" %>
          <p class="text-center text-blue-700;" style="color:#1a5294;">W. FORCE</p>
        <% end %>
      </div>
    </div>
  </div>
  <%= render template: "search/search_bar" %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SapiEevint</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="flex flex-col">

      <%# move this to partial <%= render "shared/flashes" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%# move this to partial %>
      <div data-controller="modal" class="lg:hidden fixed z-20 w-full h-full bg-black bg-opacity-70 text-white flex flex-col  p-6">
        <p data-modal-target="list" class="text-center mb-4 w-44 mt-24 ml-16">Notice: This web app is not optimized for mobile devices. For the best experience, please use a desktop or laptop.</p>
        <button data-action="click->modal#close" class="close-btn bg-red-500 hover:bg-red-600 px-4 py-2 rounded focus:outline-none w-44 mt-2 ml-16">Close</button>
      </div>
      <%= render partial: "layouts/navbar" unless action_name == "home" && controller_name == "contracts" %>
        <div class="flex flex-row">
          <%= yield %>
        </div>
        <%= turbo_frame_tag "modal" %>
    </div>
  </body>
</html>